vich_uploader:
    db_driver: orm

    mappings:
       medias:
           uri_prefix: /medias/images
           upload_destination: '%media_directory%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
