vich_uploader:
    db_driver: orm

    mappings:
       medias:
           uri_prefix: /medias/images
           upload_destination: '%kernel.project_dir%/public/medias/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
